# Lecture 0.1: Intro to Pandas 🐼 DataFrames & Series for Machine Learning 

Before we dive into our first algorithm—**k-Nearest Neighbors (k-NN)**—we must establish a solid foundation in **Pandas**. 

In Machine Learning, real-world data rarely comes as raw arrays. Whether you are dealing with structured tabular datasets, labeled feature sets, or mixed-type raw files (CSVs, Excels), data is organized using **Pandas DataStructures (`DataFrame` & `Series`)**.

### Why Pandas for Machine Learning?
1. **Labeled Data & Feature Management**: Unlike NumPy's plain numerical arrays, Pandas allows us to store named columns (features) and index-aligned rows (samples), making feature selection and target isolation clear and readable.
2. **Seamless Data Handling & Preprocessing**: It provides powerful built-in functions to easily clean missing values, handle categorical features, rename variables, and merge datasets before model training.
3. **NumPy Integration**: Pandas is built directly on top of NumPy. You can effortlessly extract raw matrices using `.to_numpy()` or `.values` whenever your algorithm requires direct matrix operations (like calculating k-NN distance matrices).

---
### Comparison summary: NumPy vs Pandas

| Concept | NumPy (`ndarray`) | Pandas (`DataFrame` / `Series`) |
| :--- | :--- | :--- |
| **Primary Focus** | N-Dimensional numerical calculations & matrix math | Tabular data manipulation, cleaning & feature engineering |
| **Data Types** | Homogeneous (all elements must be the same type) | Heterogeneous (columns can hold integers, floats, strings, etc.) |
| **Indexing** | Integer-position based (`0, 1, 2...`) | Named labels (Column names) + Index labels / Positions (`loc`, `iloc`) |
| **Role in ML** | Distance metrics, loss functions, linear algebra | Loading raw datasets, Exploratory Data Analysis (EDA), missing data handling, encoding |

# What is EDA? (Exploratory Data Analysis) 🔍

 It is a critical foundational step in any **Machine Learning** or **Data Science** project, performed right after collecting data and before training any models.

### What is the Main Purpose of EDA?
1. **Understand the Data**: Inspect the structure, data types (`dtypes`), and dimensions (`shape`) of the dataset.
2. **Detect Data Issues**: Identify missing values (`Missing Values`), duplicate rows, or extreme anomalies (`Outliers`).
3. **Discover Patterns & Relationships**: Uncover correlations between variables (e.g., finding which features strongly influence the target).
4. **Define Features and Targets**: Clearly separate input feature columns (`Features - X`) from the target prediction column (`Target - Y`).

### The Role of Pandas in EDA:
**Pandas** is the core tool used to perform EDA efficiently using built-in methods such as:
- `df.info()`: To check data types and non-null value counts.
- `df.describe()`: To generate descriptive statistics (mean, standard deviation, min, max, percentiles).
- `df.isnull().sum()`: To calculate the total missing values per column.
- Often combined with visualization libraries like `Matplotlib` and `Seaborn` to visually plot and analyze these insights.

## 1. Importing Libraries & Creating Data Structures

Pandas provides two main data structures:
- **Series**: A 1D labeled array capable of holding any data type.
- **DataFrame**: A 2D labeled data structure with columns of potentially different types (similar to a table/spreadsheet).

In [2]:
# Importing Libraries & Creating Data Structures
import pandas as pd
import numpy as np

# 1. Creating a Pandas Series
data_series = pd.Series([10, 20, 30, 40], name="Feature_Values")
print("--- Pandas Series ---")
print(data_series)

# 2. Creating a Pandas DataFrame from a dictionary
# np.nan is used to represent missing values in the dataset.
raw_data = {
    'Age': [25, 30, np.nan, 35, 40, 22, 38],
    'Salary': [50000, 60000, 52000, np.nan, 85000, 48000, 72000],
    'Department': ['IT', 'HR', 'IT', 'Finance', 'HR', 'IT', 'Finance'],
    'Purchased': ['No', 'Yes', 'No', 'Yes', 'Yes', 'No', 'Yes']
}

df = pd.DataFrame(raw_data)
print("\n--- Pandas DataFrame ---")
print(df)

--- Pandas Series ---
0    10
1    20
2    30
3    40
Name: Feature_Values, dtype: int64

--- Pandas DataFrame ---
    Age   Salary Department Purchased
0  25.0  50000.0         IT        No
1  30.0  60000.0         HR       Yes
2   NaN  52000.0         IT        No
3  35.0      NaN    Finance       Yes
4  40.0  85000.0         HR       Yes
5  22.0  48000.0         IT        No
6  38.0  72000.0    Finance       Yes

## 2. Inspecting the Dataset

Before training machine learning models, you need to understand the structure, types, and summary statistics of your dataset.

- `df.head(n)`: View the first $n$ rows.
- `df.tail(n)`: View the last $n$ rows.
- `df.info()`: Get concise summary of DataFrame (data types, non-null counts).
- `df.describe()`: Compute summary statistics (mean, std, min, max, quantiles).
- `df.shape`: Get dimensions of DataFrame (rows, columns).

In [3]:
# Import required libraries
import pandas as pd
import numpy as np

# 1. Creating a Pandas Series
data_series = pd.Series([10, 20, 30, 40], name="Feature_Values")
print("--- Pandas Series ---")
print(data_series)

# 2. Creating a Pandas DataFrame from a dictionary
raw_data = {
    'Age': [25, 30, np.nan, 35, 40, 22, 38],
    'Salary': [50000, 60000, 52000, np.nan, 85000, 48000, 72000],
    'Department': ['IT', 'HR', 'IT', 'Finance', 'HR', 'IT', 'Finance'],
    'Purchased': ['No', 'Yes', 'No', 'Yes', 'Yes', 'No', 'Yes']
}

df = pd.DataFrame(raw_data)
print("\n--- Pandas DataFrame ---")
print(df)

--- Pandas Series ---
0    10
1    20
2    30
3    40
Name: Feature_Values, dtype: int64

--- Pandas DataFrame ---
    Age   Salary Department Purchased
0  25.0  50000.0         IT        No
1  30.0  60000.0         HR       Yes
2   NaN  52000.0         IT        No
3  35.0      NaN    Finance       Yes
4  40.0  85000.0         HR       Yes
5  22.0  48000.0         IT        No
6  38.0  72000.0    Finance       Yes


Note=> How `df.describe()` Handles Missing Values (`NaN`)
- **Automatic Exclusion**: `df.describe()` automatically ignores and excludes all `NaN` (missing) values when calculating statistics (like mean, std, min, max, and percentiles) for each column.
- **No Data Mutation**: It does **not** modify or drop rows from your original DataFrame; it simply computes the metrics based only on the valid (non-null) data points available in each column.
- **Impact on Count**: You can verify this by looking at the `count` row in the summary output. If a column has missing values, its `count` will be lower than the total number of rows in the DataFrame.

## 3. Data Selection, Slicing & Indexing

Selecting relevant features (columns) and samples (rows) is crucial for preparing your dataset for machine learning.

- `df['column_name']`: Select a single column as a Series.
- `df[['col1', 'col2']]`: Select multiple columns as a DataFrame
- `df.loc[row_label, col_label]`: Label-based selection.
- `df.iloc[row_index, col_index]`: Integer index-based selection.
# 🔍 `.loc` vs `.iloc`
| Feature / Aspect | `.loc` (Label-Based Indexing) | `.iloc` (Integer-Position-Based Indexing) |
| :--- | :--- | :--- |
| **Core Concept** | Accesses data using explicit **labels** of rows and columns (e.g., string names, dates, or custom index keys). | Accesses data strictly using integer **ordinal positions** from `0` to `n-1`, ignoring custom index names. |
| **Index Types Supported** | Strings, integers (if explicitly set as labels), DatetimeIndex, MultiIndex, and boolean arrays. | Integer positions only (`int`, lists of integers, integer slices), or boolean NumPy arrays. |
| **Slicing Endpoint** | **Inclusive** (`start:end` includes both `start` and `end` labels if they exist). | **Exclusive** (`start:end` includes `start` up to `end - 1`, following standard Python convention). |
| **Missing / Invalid Indexing** | Raises a `KeyError` if a specified row or column label does not exist in the DataFrame. | Raises an `IndexError` if the integer position exceeds the bounds of the axis dimensions. |
| **Boolean Filtering Support** | **Native & Direct**: Can directly accept boolean Series or lists aligned with the DataFrame index. | **Requires Conversion**: Direct boolean Series pass fails; requires converting to a NumPy array via `.to_numpy()` or `.values`. |
| **Callable / Lambda Support** | Fully supports callable functions (e.g., `df.loc[lambda df: df['Age'] > 25]`) for chaining. | Fully supports callable functions (e.g., `df.iloc[lambda df: [0, 2]]`) for pipeline processing. |
| **Performance (Speed)** | Slightly slower when resolving string labels, hash map lookups, or multi-indexes. | **Faster**: Operates directly on contiguous integer memory arrays and underlying NumPy matrix coordinates. |
| **Primary Machine Learning Use Case** | Extracting data subsets using feature names, class labels, or specific date-time ranges during preprocessing. | Slicing raw matrix shapes, splitting feature matrices (`X`) and targets (`y`) by numerical column positions. |

In [24]:
import pandas as pd

# ==========================================
# LOADING REAL HOUSE PRICES DATASET FROM LIVE URL
# ==========================================
# Direct public URL for a real House Prices CSV dataset
url = "https://raw.githubusercontent.com/reisanar/datasets/master/kaggle-housing.csv"
# Read the dataset directly into a Pandas DataFrame
df = pd.read_csv(url)
# 2. EXPLORATORY DATA ANALYSIS (EDA)
print(f"\nDataset Shape (Rows, Columns): {df.shape}\n")
print("-------- 2. Dataset Info --------")
df.info()
print("\n------- 3. Statistical Summary --------")
print(df.describe())

--- 1. First 5 Rows of Kaggle Housing Dataset ---

Dataset Shape (Rows, Columns): (545, 13)

-------- 2. Dataset Info --------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   price             545 non-null    int64
 1   area              545 non-null    int64
 2   bedrooms          545 non-null    int64
 3   bathrooms         545 non-null    int64
 4   stories           545 non-null    int64
 5   mainroad          545 non-null    object
 6   guestroom         545 non-null    object
 7   basement          545 non-null    object
 8   hotwaterheating   545 non-null    object
 9   airconditioning   545 non-null    object
 10  parking           545 non-null    int64
 11  prefarea          545 non-null    object
 12  furnishingstatus  545 non-null    object
dtypes: int64(6), object(7)
memory usage: 55.5+ KB

------- 3. Statistical Summary --------
              price          area    bedrooms   bathrooms     stories  \
count  5.450000e+02    545.000000  545.000000  545.000000  545.000000
mean   4.766729e+06   5150.541284    2.965138    1.286239    1.805505
std    1.870440e+06   2170.141023    0.738064    0.502470    0.867492
min    1.750000e+06   1650.000000    1.000000    1.000000    1.000000
25%    3.430000e+06   3600.000000    2.000000    1.000000    1.000000
50%    4.340000e+06   4600.000000    3.000000    1.000000    2.000000
75%    5.740000e+06   6360.000000    3.000000    2.000000    2.000000
max    1.330000e+07  16200.000000    6.000000    4.000000    4.000000

          parking
count  545.000000
mean     0.693578
std      0.861586
min      0.000000
25%      0.000000
50%      0.000000
75%      1.000000
max      3.000000

In [25]:
print("--- 1. First 5 Rows of Kaggle Housing Dataset ---")
df.head(5)

--- 1. First 5 Rows of Kaggle Housing Dataset ---

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished

In [5]:
# ==========================================
# 3. SELECTING FEATURES AND TARGET FOR ML
# ==========================================
# In Machine Learning tasks, we isolate our feature matrix (X) from the target price (y)

# Feature Matrix (Independent Variables) - renamed to 'house_features'
house_features = df[['area', 'bedrooms', 'bathrooms', 'stories']] # feature matrix (X)
print("--- House Features Matrix Head ---")
print(house_features.head(5))

# Target Vector (Dependent Variable / What we want to predict) 'target_price'
target_price = df['price'] # target vector (y)
print("\n--- Target Price Vector Head ---")
print(target_price.head(5))

# Checking the types of the feature matrix and target vector
print("\n--- Types of features and target ---")
print(type(house_features))  # Output: <class 'pandas.core.frame.DataFrame'>
print(type(target_price))   # Output: <class 'pandas.core.series.Series'>

--- House Features Matrix Head ---
   area  bedrooms  bathrooms  stories
0  7420         4          2        3
1  8960         4          4        4
2  9960         3          2        2
3  7500         4          2        2
4  7420         4          1        2

--- Target Price Vector Head ---
0    13300000
1    12250000
2    12250000
3    12215000
4    11410000
Name: price, dtype: int64

--- Types of features and target ---
<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.series.Series'>

In [22]:
# ==================================================
# PART 1: ADVANCED EXAMPLES USING .loc (Label-Based)
# ==================================================

# Example 1: Select specific non-consecutive rows and specific columns by name
# Useful when you want to inspect particular samples (e.g., houses with index 0, 2, and 4)
print("--- .loc Example 1: Specific Rows and Columns ---")
print(df.loc[[0, 2, 4], ['price', 'area', 'bedrooms']]) 
# note [[0, 2, 4]] is a list of row labels, and ['price', 'area', 'bedrooms'] is a list of column labels
print("\n" + "_"*50 + "\n")


# Example 2: Inclusive Slicing (Range of rows)
# Notice that row index 2 IS included in the output (Unlike Python/iloc slicing)
print("--- .loc Example 2: Inclusive Range Slicing ---")
print(df.loc[0:2, ['area', 'price']])
print("\n" + "_"*50 + "\n")


# Select specific columns (price, bedrooms) only for houses where bedrooms > 3
print("--- .loc Example 3: Filtering with Conditions ---")
print(df.loc[df['bedrooms'] > 3, ['price', 'bedrooms', 'area']].head(3))
print("\n" + "_"*50 + "\n")

print("--- Range using .loc (Inclusive of end) ---")
# Example 4: Select rows from index 0 to index 3 (Row 3 WILL appear in the output)
# And select a range of columns from 'area' up to 'stories'
print(df.loc[0:3, 'area':'stories'])
print("\n" + "_"*50 + "\n")

# ======================================================
# PART 2: ADVANCED EXAMPLES USING .iloc (Position-Based)
# ======================================================

# Example 1: Select a single exact value using integer coordinates
# Row position 1, Column position 0 (first column)
print("--- .iloc Example 1: Single Cell Value ---")
print(df.iloc[1, 0])
print("\n" + "_"*50 + "\n")

# Example 2: Exclusive Slicing (Range of positions)
# Rows from 0 up to 3 (Excludes index 3, so rows 0, 1, 2) and columns 0 to 2
print("--- .iloc Example 2: Exclusive Slicing ---")
print(df.iloc[0:3, 0:3])
print("\n" + "_"*50 + "\n")

# Example 3: Selecting specific scattered rows and columns using integer lists
# Grabbing row positions 0, 5, 10 and column positions 0, 1, 3
print("--- .iloc Example 3: Custom Lists of Positions ---")
print(df.iloc[[0, 5, 10], [0, 1, 3]])


# Example 4: Range / Slicing WITH .iloc (Position-Based)
# Rule: The ending position IS EXCLUSIVE.

print("--- Range using .iloc (Exclusive of end) ---")
# Select row positions from 0 up to 3 (Rows 0, 1, and 2 will appear, but row 3 is EXCLUDED)
# And select column positions from 0 up to 3 (Columns 0, 1, and 2)
print(df.iloc[0:3, 0:3])

--- .loc Example 1: Specific Rows and Columns ---
      price  area  bedrooms
0  13300000  7420         4
2  12250000  9960         3
4  11410000  7420         4

__________________________________________________

--- .loc Example 2: Inclusive Range Slicing ---
   area     price
0  7420  13300000
1  8960  12250000
2  9960  12250000

__________________________________________________

--- .loc Example 3: Filtering with Conditions ---
      price  bedrooms  area
0  13300000         4  7420
1  12250000         4  8960
3  12215000         4  7500

__________________________________________________

--- Range using .loc (Inclusive of end) ---
   area  bedrooms  bathrooms  stories
0  7420         4          2        3
1  8960         4          4        4
2  9960         3          2        2
3  7500         4          2        2

__________________________________________________

--- .iloc Example 1: Single Cell Value ---
12250000

__________________________________________________

--- .iloc Example 2: Exclusive Slicing ---
      price  area  bedrooms
0  13300000  7420         4
1  12250000  8960         4
2  12250000  9960         3

__________________________________________________

--- .iloc Example 3: Custom Lists of Positions ---
       price   area  bathrooms
0   13300000   7420          2
5   10850000   7500          3
10   9800000  13200          1
--- Range using .iloc (Exclusive of end) ---
      price  area  bedrooms
0  13300000  7420         4
1  12250000  8960         4
2  12250000  9960         3

## 4. Conditional Filtering

Filtering rows based on specific conditions helps clean data and isolate subsets for evaluation.

In [7]:
# ==========================================
# 4. CONDITIONAL FILTERING IN PANDAS
# ==========================================

# Condition 1: Filter houses where the number of bedrooms is strictly greater than 4
# ==============================================================================
# 1. Define the specific columns we want to display
selected_columns = ['area', 'bedrooms', 'bathrooms', 'stories', 'basement', 'price']

# 2. Filter for houses with 4 or more bedrooms, select specific columns, and group by 'bedrooms'
high_bedroom_houses = df.loc[df['bedrooms'] > 4, selected_columns]
print("--- Houses with More Than 4 Bedrooms ---")
print(high_bedroom_houses)  # Display only the feature columns for these houses
print(f"Number of houses with more than 4 bedrooms: {high_bedroom_houses['bedrooms'].count()}")
print("\n" + "-"*50 + "\n")

# Condition 2: Multiple Conditions using AND (&) and OR (|) operator
# ==============================================================================
# Note: Each condition must be wrapped in parentheses  () in Pandas.
# Let's filter houses that have bedrooms > 3 AND price > 10,000,000
luxury_large_houses = df[(df['bedrooms'] > 3) & (df['price'] > 10000000)]

print("--- 2. Multiple Conditions Filtering (AND operator) ---")
print(luxury_large_houses[selected_columns])  # Display only the feature columns for these houses
print(f"Total matching luxury houses: {luxury_large_houses.shape[0]}")
print("\n" + "-"*50 + "\n")

--- Houses with More Than 4 Bedrooms ---
      area  bedrooms  bathrooms  stories basement     price
7    16200         5          3        2       no  10150000
28    7950         5          2        2      yes   8400000
34    6840         5          1        2      yes   8120000
89    8580         5          3        2       no   6440000
112   4300         6          2        2       no   6083000
143   4800         5          2        3      yes   5600000
152   5400         5          1        2      yes   5565000
271   1905         5          1        2      yes   4340000
340   5300         5          2        2       no   3850000
356   2520         5          2        1      yes   3773000
395   3600         6          1        2       no   3500000
536   3420         5          1        2       no   1960000
Number of houses with more than 4 bedrooms: 12

--------------------------------------------------

--- 2. Multiple Conditions Filtering (AND operator) ---
    area  bedrooms  bathrooms  stories basement     price
0   7420         4          2        3       no  13300000
1   8960         4          4        4       no  12250000
3   7500         4          2        2      yes  12215000
4   7420         4          1        2      yes  11410000
6   8580         4          3        4       no  10150000
7  16200         5          3        2       no  10150000
Total matching luxury houses: 6

--------------------------------------------------

## 5. Handling Missing Data

Most Machine Learning algorithms cannot handle missing values (`NaN`). We must detect and either remove or impute them.

- `df.isnull().sum()`: Count missing values per column.
- `df.dropna()`: Remove rows with missing data.
- `df.fillna(value)`: Impute missing values with a constant or mean/median.

### Practical Example: Simulating and Fixing Missing Data

Since our original Kaggle housing dataset is clean and contains no missing values, we will **intentionally inject some `NaN` values** into a copy of the data for educational purposes to demonstrate how to detect and handle missing values in real-world machine learning projects.

In [8]:
# ==============================================================================
# PRACTICAL EXAMPLE: Random Sampling with a Fixed Seed and Injecting NaNs
# ==============================================================================
import numpy as np

# 1. Take a random sample of 50 rows with a fixed seed for reproducibility,
# and reset the index so row positions are clean and sequential (0 to 49)
df_simulated = df.sample(n=50, random_state=42).reset_index(drop=True).copy()

# 2. Intentionally inject 3 NaN values into different rows and columns
df_simulated.loc[5, 'area'] = np.nan       # Inject NaN into row 5, 'area' column
df_simulated.loc[18, 'price'] = np.nan     # Inject NaN into row 18, 'price' column
df_simulated.loc[32, 'bedrooms'] = np.nan  # Inject NaN into row 32, 'bedrooms' column

print("--- Step 1: Sample Dataset (50 rows) with 3 Injected NaN Values ---")
# Display rows where we injected NaNs to verify
print(df_simulated[['area', 'bedrooms', 'price']].head(20))  # Display first 20 rows to include the injected NaNs
print("\n" + "-"*50 + "\n")

--- Step 1: Sample Dataset (50 rows) with 3 Injected NaN Values ---
      area  bedrooms       price
0   5900.0       4.0   4060000.0
1   6500.0       3.0   6650000.0
2   4040.0       2.0   3710000.0
3   5000.0       3.0   6440000.0
4   3960.0       3.0   2800000.0
5      NaN       3.0   4900000.0
6   8520.0       3.0   5250000.0
7   4990.0       4.0   4543000.0
8   3240.0       2.0   2450000.0
9   2700.0       3.0   3353000.0
10  8580.0       4.0  10150000.0
11  3934.0       2.0   2660000.0
12  3720.0       2.0   3360000.0
13  3100.0       3.0   3360000.0
14  3970.0       3.0   2275000.0
15  3630.0       3.0   2660000.0
16  2000.0       2.0   2660000.0
17  6000.0       3.0   7350000.0
18  5850.0       3.0         NaN
19  6000.0       2.0   2870000.0

--------------------------------------------------

In [9]:
# Create a copy for imputation
df_clean = df_simulated.copy()

# ==============================================================================
# DETECTING AND FIXING THE MISSING VALUES
# ==============================================================================

# Detect missing values by counting nulls per column
print("--- Step 1: Counting Missing Values ---")
print(df_simulated.isnull().sum())
print("\n" + "-"*50 + "\n")

# Impute (Fill) the missing values:
# - Fill missing 'price' with the column mean
df_clean['price'] = df_clean['price'].fillna(df_clean['price'].mean())

# - Fill missing 'area' with the column mean
df_clean['area'] = df_clean['area'].fillna(df_clean['area'].mean())

# - Fill missing 'bedrooms' with the column median
df_clean['bedrooms'] = df_clean['bedrooms'].fillna(df_clean['bedrooms'].median())


# Dropping rows with missing values (Alternative approach)
df_dropped = df_clean.dropna()

print("--- Step 2: Verification After Imputation (Total Missing Values) ---")
print(df_clean.isnull().sum())

print("\n" + "-"*50 + "\n")

print("--- Displaying Specific Values After Imputation ---")
print(f"Value in row 5, 'area' column: {df_clean.loc[5, 'area']}")
print(f"Value in row 18, 'price' column: {df_clean.loc[18, 'price']}")
print(f"Value in row 32, 'bedrooms' column: {df_clean.loc[32, 'bedrooms']}")

--- Step 1: Counting Missing Values ---
price               1
area                1
bedrooms            1
bathrooms           0
stories             0
mainroad            0
guestroom           0
basement            0
hotwaterheating     0
airconditioning     0
parking             0
prefarea            0
furnishingstatus    0
dtype: int64

--------------------------------------------------

--- Step 2: Verification After Imputation (Total Missing Values) ---
price               0
area                0
bedrooms            0
bathrooms           0
stories             0
mainroad            0
guestroom           0
basement            0
hotwaterheating     0
airconditioning     0
parking             0
prefarea            0
furnishingstatus    0
dtype: int64

--------------------------------------------------

--- Displaying Specific Values After Imputation ---
Value in row 5, 'area' column: 5126.244897959184
Value in row 18, 'price' column: 4586000.0
Value in row 32, 'bedrooms' column: 3.0

## 6. Data Cleaning & Feature Transformation

Preparing data for Machine Learning involves transforming columns, adding new features, and encoding categorical variables.

- `df.rename()`: Rename column headers.
- `df.drop()`: Drop unnecessary features.
- `df.astype()`: Convert data types.

In [26]:
# ==========================================
# 6. SIMPLE DATA CLEANING & TRANSFORMATION
# ==========================================

# 1. Create a clean copy of the dataset to keep the original safe
df_cleaned = df.copy()
# 2. Rename a column (e.g., change 'stories' to 'num_floors')
df_cleaned = df_cleaned.rename(columns={'stories': 'num_floors'})
print("-> Column 'stories' renamed to 'num_floors'.")
# 3. Convert data type (e.g., convert 'area' to float)
df_cleaned['area'] = df_cleaned['area'].astype(float)
print("-> Column 'area' converted to float.")

# 4. Convert text columns (like 'mainroad') into numbers (0 and 1) using One-Hot Encoding

"""anthor approach is to use labelencoder like LabelEncoder() from sklearn.preprocessing, 
   but here we will use a simple map function for binary columns.""" 

if 'mainroad' in df_cleaned.columns:
    df_cleaned['mainroad'] = df_cleaned['mainroad'].map({'yes': 1, 'no': 0})
    print("-> 'mainroad' encoded quickly using map (yes=1, no=0)")

# Preview the first 3 rows of our clean dataset
print("\n--- Preview of Cleaned Dataset ---")
df_cleaned[['area', 'num_floors', 'bedrooms', 'bathrooms', 'mainroad', 'price']].head(3)

-> Column 'stories' renamed to 'num_floors'.
-> Column 'area' converted to float.
-> 'mainroad' encoded quickly using map (yes=1, no=0)

--- Preview of Cleaned Dataset ---

     area  num_floors  bedrooms  bathrooms  mainroad     price
0  7420.0           3         4          2         1  13300000
1  8960.0           4         4          4         1  12250000
2  9960.0           2         3          2         1  12250000

### Encoding Categorical Data using LabelEncoder 
We can use `LabelEncoder` from Scikit-Learn to quickly transform text columns into numerical values.

> ```python
> from sklearn.preprocessing import LabelEncoder
> 
> # Initialize the Label Encoder
> le = LabelEncoder()
> 
> # Transform the text column ('mainroad') into numbers automatically
> df_cleaned['mainroad'] = le.fit_transform(df_cleaned['mainroad'])
> ```

### 1. What is Data Mapping? (General Concept)

In data science, **Mapping** is the process of creating a direct correspondence or bridge between elements of one dataset category and a target format. 

Think of it like a translation dictionary: you take raw, qualitative values (such as text labels like `"Yes"`, `"No"`) and **map** them precisely to a quantitative scale (`1`, `0`) so that analytical systems and machine learning models can process them.

---

### 2. Why is Mapping Important?

- **Standardization:** Unifies inconsistent data formats into a clean, uniform structure.
- **Data Translation:** Converts words and categories into numbers required for statistical analysis.
- **Precision & Control:** Gives you 100% manual control over how each specific category translates.

---

### 3. Mapping in Python & Pandas (`.map()`)

In Python, we implement mapping using the `.map()` method on a Pandas Series. It allows us to transform values within the same column instantly.

#### **Function Parameters:**
The `Series.map()` function accepts the following main arguments:

1. **`arg` (Required):** The mapping correspondence. It can be:
   - A **Dictionary** (e.g., `{'yes': 1, 'no': 0}`) where keys are existing values and values are the new mapped targets.
   - A **Function** or a **Lambda expression** (e.g., `lambda x: x.lower()`) applied to each element.
   - A **Series** containing the corresponding mappings.
2. **`na_action` (Optional):** Controls how missing values (`NaN`) are handled.
   - Setting `na_action='ignore'` skips missing values and leaves them as `NaN` instead of trying to map them.

### 7. Grouping & Aggregation (`groupby`)

In exploratory data analysis and feature engineering, grouping data allows us to calculate summary statistics across categorical segments. This helps us uncover hidden patterns and relationships between features and the target variable.

- **`df.groupby('column')`**: Splits the data into groups based on unique categories.
- **`.mean()`, `.sum()`, `.count()`**: Standard aggregate functions applied to the groups.
- **`.agg()`**: Applies multiple aggregation functions simultaneously (e.g., mean, max, count).

In [31]:
# ==========================================
# 7. GROUPING & AGGREGATION EXAMPLES
# ==========================================

# 1. Group by a categorical feature (e.g., 'num_floors') and find the average price
if 'price' in df_cleaned.columns and 'num_floors' in df_cleaned.columns:
    avg_price_by_floors = df_cleaned.groupby('num_floors')['price'].mean().reset_index()
    print("--- Average Price by Number of Floors ---")
    print(avg_price_by_floors)

# 2. Using .agg() to calculate multiple metrics (mean, count, max) for a group
if 'price' in df_cleaned.columns and 'mainroad' in df_cleaned.columns:
    summary_stats = df_cleaned.groupby('mainroad')['price'].agg(['mean', 'count', 'max'])
    print("\n--- Price Summary Statistics by Mainroad Access ---")
    print(summary_stats)

--- Average Price by Number of Floors ---
   num_floors         price
0           1  4.170659e+06
1           2  4.764074e+06
2           3  5.685436e+06
3           4  7.208450e+06

--- Price Summary Statistics by Mainroad Access ---
                  mean  count       max
mainroad
0         3.398905e+06     77   5600000
1         4.991777e+06    468  13300000

## 8. Exporting Processed Data

Once your dataset is cleaned and engineered, save it for training models.

In [29]:
# Export the cleaned DataFrame to a CSV file without the row index
df_cleaned.to_csv("df_cleaned.csv", index=False)
print("Successfully saved cleaned dataset to 'df_cleaned.csv'!")

Successfully saved cleaned dataset to 'df_cleaned.csv'!

### 9. Integrating SQL with Pandas for Data Science

In real-world data science pipelines, data rarely lives in local CSV files. Instead, it resides in relational databases. Pandas integrates seamlessly with SQL, allowing us to query, filter, and aggregate large datasets directly into a Pandas `DataFrame` using `pd.read_sql()`.
 
- **SQL vs. Pandas Grouping:** SQL handles heavy data extraction, filtering (`WHERE`), and aggregation (`GROUP BY`) at the database level.
- **Pandas Role:** Takes the resulting clean dataset and prepares it for Machine Learning preprocessing (cleaning, encoding, splitting).

In [32]:
# ==============================================================================
#9.SQL & PANDAS INTEGRATION (Practical Example)
# ==============================================================================
import sqlite3
import pandas as pd

# 1. Create a temporary in-memory SQLite database connection for demonstration
conn = sqlite3.connect(':memory:')

# Push our current df_cleaned to the SQL database as a table named 'housing_table'
df_cleaned.to_sql('housing_table', conn, index=False, if_exists='replace')

# 2. Write an SQL query mimicking GROUP BY and aggregate functions
sql_query = """
    SELECT num_floors, AVG(price) AS avg_price, COUNT(*) as total_houses
    FROM housing_table
    GROUP BY num_floors
    ORDER BY avg_price DESC;
"""

# 3. Read the SQL query results directly into a new Pandas DataFrame
df_from_sql = pd.read_sql(sql_query, conn)

# 4. Close the database connection
conn.close()

# Preview the resulting DataFrame from SQL
print("--- Aggregated Data Fetched via SQL into Pandas ---")
print(df_from_sql)

--- Aggregated Data Fetched via SQL into Pandas ---
   num_floors     avg_price  total_houses
0           4  7.208450e+06            41
1           3  5.685436e+06            39
2           2  4.764074e+06           238
3           1  4.170659e+06           227